name: Setup pnpm

on: [workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Setup pnpm
        uses: pnpm/action-setup@53751a9789c7351e4924f01fe68370252a4f1f18
        with:
          version: 'latest'
      - name: Verify pnpm
        run: pnpm -v
